# Database configuration
spring:
  datasource:
    url: jdbc:<your-database-driver>://<your-database-host>:<your-database-port>/<your-database-name>
    username: <your-database-username>
    password: <your-database-password>

# Initial admin configuration (an admin will be inserted into the database when the application starts)
initialAdmin:
  username: <your-admin-username>
  password: <your-admin-password>
