spring:
  profiles:
    active:
      - dev # Change to `prod` when deploying to production
  application:
    name: warehouse_management # Change this to your application name
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type: trace
  output:
    ansi:
      enabled: always
